---

alertmanager:
  enabled: true

prometheus:
  prometheusSpec:
    ruleNamespaceSelector: {}
      #matchExpressions:
      #  - key: name
      #    operator: in
      #    values:
      #      - monitoring
      #      - mongodb
    ruleSelector:
      matchLabels:
        release: prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: prometheus

grafana:
  enabled: true
  adminPassword: prom-operator
  defaultDashboardsEnabled: true
  additionalDataSources: []
