---

prometheus:
  prometheusSpec:
    ruleNamespaceSelector:
      matchNames:
        - monitoring
    ruleSelector:
      matchLabels:
        release: prometheus
    serviceMonitorNamespaceSelector:
      matchNames:
        - monitoring
    serviceMonitorSelector:
      matchLabels:
        release: prometheus

grafana:
  enabled: true
  adminPassword: prom-operator
  defaultDashboardsEnabled: true
  additionalDataSources: []
