---

prometheus:
  prometheusSpec:
    ruleNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        release: prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: prometheus

grafana:
  enabled: true
  adminPassword: prom-operator
  defaultDashboardsEnabled: true
  additionalDataSources: []
