---

prometheus:
  prometheusSpec:
    ruleNamespaceSelector:
      matchExpressions:
        - key: name
          operator: in
          values:
            - monitoring
            - mongodb
    ruleSelector:
      matchLabels:
        release: prometheus
    serviceMonitorNamespaceSelector:
      matchExpressions:
        - key: name
          operator: in
          values:
            - monitoring
            - mongodb
    serviceMonitorSelector:
      matchLabels:
        release: prometheus

grafana:
  enabled: true
  adminPassword: prom-operator
  defaultDashboardsEnabled: true
  additionalDataSources: []
