---

repositories:
  - name: nginx-stable
    url: https://helm.nginx.com/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  # k create namespace monitoring
  # helm install --version 14.4.0 prometheus prometheus-community/kube-prometheus-stack -f values/prometheus.yaml -n monitoring
  - name: prometheus
    installed: true
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 14.5.0
    values:
      - values/prometheus.yaml
  # k create namespace mongodb
  # helm install --version 10.11.1 mongodb bitnami/mongodb -f values/mongodb.yaml -n mongodb
  - name: mongodb
    installed: true
    namespace: mongodb
    chart: bitnami/mongodb
    version: 10.11.2
    needs:
      - monitoring/prometheus
    values:
      - values/mongodb.yaml
