---

repositories:
  - name: nginx-stable
    url: https://helm.nginx.com/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: kube-state-metrics
    url: https://kubernetes.github.io/kube-state-metrics
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-stack
    installed: true
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 14.4.0
  - name: mongodb
    needs:
      - prometheus-stack
    installed: false
    namespace: mongodb
    chart: bitnami/mongodb
    version: 10.11.1
    values:
      - values/mongodb.yaml
